### ISSUE TITLE
Broken extension and another.

### ISSUE THREAD

**Issue by Archon332** [ffxvs/sd-webui-complete-setup#27]
Grettings.

You are my savior with your paperspace SD launcher.

I have a problem: Adetailer doesn't work correctly.

Firstly, I have this error in the WebUI lauching cell, and also CUDA is out of memory with A4000 at higher upscaling rate (1.5) during Adetailer part of generating. Without Adetailer everything is OK. I never had this error with A4000 and RTX5000 on Paperspace before. But at lower upscaling rate it works at least. 

![Image](https://github.com/user-attachments/assets/ff571146-2db7-4080-b6f8-4d4229766a26)
![Image](https://github.com/user-attachments/assets/19c819f8-41d0-4354-b6c8-9ec24a4d66c8)
![Image](https://github.com/user-attachments/assets/e4b5dfca-41f1-4dfc-83fd-d9c8de80ce00)

And some images look like extension doesn't even started to work at masked part of image. And there is no errors in the cell. This never happened on the notebook with standard container. And settings of Adetailer same for both images.

![Image](https://github.com/user-attachments/assets/ae6c5978-b139-4776-beb0-d3bc986d264d)
![Image](https://github.com/user-attachments/assets/ca5a2487-9da6-4c0a-af70-11edc54a0b03)
I'm sorry for NSFW image, I hope cutted version will not make any troubles.
Previously adetailer worked great with all same prompts, model, settings etc.

And also I have two abother questions. 
1)  How can I add -no-half-vae argument to launching settings?
2) And how make deleting command with sudo work? In the the old notebook with standard Paperspace container this worked. This is needed to delete whole folders without deleting every single file manually. And also for for cleaning hidden ".Trash" folder. 

![Image](https://github.com/user-attachments/assets/944d7c7c-3151-4ecf-bb55-144c73418bb2)

**Comment by ffxvs** [comment]
Thank you for reporting this issue. I will follow up when I'm on my pc soon.

**Comment by ffxvs** [comment]
> ![Image](https://github.com/user-attachments/assets/60115cde-69f3-44e0-b1ae-c40ce58b20da)

From this image, it looks like the Adetailer installation is broken. I suggest you to delete the Adetailer directory in `notebooks/stable-diffusion-webui/extensions/adetailer`. Just right click and delete the directory. Then install it again from the extension list.

<br>
<br>

> ![Image](https://github.com/user-attachments/assets/184d60de-d29e-4a08-a238-e70db44da576)

Are you using SDXL based model? This error occurs because you are using a corrupted SDXL VAE. To solve this issue, select `sdxl-vae-fp16-fix.safetensors` in SD VAE menu at the top. There's no need to add --no-half-vae.

<br>
<br>

> ![Image](https://github.com/user-attachments/assets/85a2417e-197a-458c-8e21-f81e986716aa)
> CUDA is out of memory with A4000 at higher upscaling rate (1.5) during Adetailer part of generating. Without Adetailer everything is OK. I never had this error with A4000 and RTX5000 on Paperspace before. But at lower upscaling rate it works at least.

It's normal to get this error when using a GPU with 16GB VRAM or less. Try enabling the `Tiled VAE` option and set the `Encoder Tile Size` to 2048. This will help to reduce the VRAM usage.

<br>
<br>

> And how make deleting command with sudo work? In the the old notebook with standard Paperspace container this worked. This is needed to delete whole folders without deleting every single file manually. And also for for cleaning hidden ".Trash" folder.

To delete a folder just use right click on the particular folder the click delete. No command needed.

Let me know if you are still facing issues.

**Comment by Archon332** [comment]
@ffxvs 
1) VAE I used before was from stabilityai's huggingface. There was no sdxl-vae-fp16-fix Vae built-in even after ''Resource Lists'' cell was ran. So, I just downloaded VAE from attached link and updloaded to notebook manually. 

![Image](https://github.com/user-attachments/assets/0c1e5d35-c210-4a8f-84f1-770fe70475a3)

**And after this there were no errors with no-half-vae and cuda memory, even without tiled-vae extension. Thank you with this.**

I use pony-based AutismMix, which is on the SDXL anime models list, but since I use confetty version and there is only pony version option in the list, I also uploaded the model manually.

But this error stared to apperar during launching WebUI.

![Image](https://github.com/user-attachments/assets/db690afc-574e-49af-911b-fb22dff608e2)

2) Deleted Adetailer and installed it again from the WebUI Extensions cell. **It is still happening**. I tried this with differrent prompts and found out that this happens mostly with NSFW prompts. Everything is fine during processig, but in the end face is bad. 

![Image](https://github.com/user-attachments/assets/b884b294-5676-4d5e-9931-db72de161e74)
![Image](https://github.com/user-attachments/assets/c96f6b94-762f-4c7b-aff1-97fc54dc3393)

And there are no errors.

![Image](https://github.com/user-attachments/assets/f64ef3f2-2e7e-4f42-b5d3-f145808cea8c)

Here are Adetailer setting if it might help.

![Image](https://github.com/user-attachments/assets/f62dfc72-32a6-48ef-9909-2ff207d1ae1e)
![Image](https://github.com/user-attachments/assets/753082bf-2b8e-4e26-809a-546e7452525c)
![Image](https://github.com/user-attachments/assets/599dc3f1-219e-4b9f-962a-55d6303313a2)
![Image](https://github.com/user-attachments/assets/e0f0bea6-f821-40df-a83a-eb34f2075884)

I will contact Adetailer developer simultaneously.

**Comment by ffxvs** [comment]
> 1. VAE I used before was from stabilityai's huggingface. There was no sdxl-vae-fp16-fix Vae built-in even after ''Resource Lists'' cell was ran. So, I just downloaded VAE from attached link and uploaded to notebook manually.

Actually, you not only need to run the cell, but also click the download button to download it even if you don't select anything from the list.

<br>

> I use pony-based AutismMix, which is on the SDXL anime models list, but since I use confetty version and there is only pony version option in the list, I also uploaded the model manually.

Since I can't keep up with the latest models, I accept requests if users want to add other models to the lists.

<br>

> But this error stared to apperar during launching WebUI.
> ![Image](https://github.com/user-attachments/assets/db690afc-574e-49af-911b-fb22dff608e2)

This is harmless warning. You can ignore it.

<br>

> 2. Deleted Adetailer and installed it again from the WebUI Extensions cell. **It is still happening**. I tried this with differrent prompts and found out that this happens mostly with NSFW prompts. Everything is fine during processig, but in the end face is bad.

I think this is a specific Adetailer issue. Contacting Adetailer dev is the best solution I think. But I can help you to try solve this issue. Send me your workflows, prompt, model, loras, extensions, etc, including the nsfw prompt. Write them in a txt file and upload it here (we can delete it later if you are concerned about privacy).

<br>

> Also, this appears during the first image generating after the launch.
> ![Image](https://github.com/user-attachments/assets/d7ab25ac-c03d-4ed9-8f8a-b93334ad7923)  

Ultralytics is a Adetailer required dependency. Everything looks good.

**Comment by Archon332** [comment]
[Image settings.txt](https://github.com/user-attachments/files/19040749/Image.settings.txt)

@ffxvs Sure, here is setting of one broken image.
Also, during testing if NegPip is the reason, I found out that if from the original ''negative'' part of main prrompt I leave only (lips:-1.1), Adetailer starts to work as it nearly should:

![Image](https://github.com/user-attachments/assets/9f6ed8b1-c4b2-4992-97ed-072de15a44e6)

With 2 of 3 negatives: (lips:-1.1) and (messy hair:-1.1) adetailer breaks, but it still look like a face:

![Image](https://github.com/user-attachments/assets/71da1133-8ddf-4e3d-b3c6-45fcc2d01e1b)

And with all 3 negatives, Adetailer breaks completely: 

![Image](https://github.com/user-attachments/assets/5cca6234-e9f8-4382-87e4-7ee3a84300db)

And I tried to print all 3 negatives in the main prompt, but leave only (lips:-1.1) in the adetailer prompt, and it worked exactly great ad it did before. 

![Image](https://github.com/user-attachments/assets/c58dc35e-e610-4425-ad23-941a615ffebd)

So, i have 2 suggestions here:
1) Adetailer started to conflict with NegPip
2) Adetailer started to depend on this (I don'r remember it's name). With 3 negatives it's 155, with 2 it's 152, and 149 with 1.

![Image](https://github.com/user-attachments/assets/5fdd6303-1e12-4f89-8be2-2411f08ea72f)

**Comment by ffxvs** [comment]
I think I found the culprit. 
As stated in [Negpip readme](https://github.com/hako-mikan/sd-webui-negpip#for-users-of-adetailer), you need to add negpip in Adetailer settings like this to make it work properly. No need to restart.

![Image](https://github.com/user-attachments/assets/42f45b72-4a17-4e42-9509-39b36e9db08e)

I've tested it and it works now.
Please confirm if this resolves the issue.

**Comment by Archon332** [comment]
> I think I found the culprit. As stated in [Negpip readme](https://github.com/hako-mikan/sd-webui-negpip#for-users-of-adetailer), you need to add negpip in Adetailer settings like this to make it work properly. No need to restart.
> 
> ![Image](https://github.com/user-attachments/assets/42f45b72-4a17-4e42-9509-39b36e9db08e)
> 
> I've tested it and it works now. Please confirm if this resolves the issue.

Wow, the solution was so close all this time. This works, thank you.
Before I close the Issue, I have another question. Is here any folders for deleted files or what deleted is deleted completely straightaway? This needed for memory managament.

**Comment by ffxvs** [comment]
No, Jupyterlab's feature to delete to trash has been disabled. I don't really remember the details, but there's a bug if this feature is enabled on Jupyterlab. And everything deleted via webui, python code, or linux command will be deleted permanently.

**Comment by Archon332** [comment]
Thank you very much than. Good luck.
